#!/usr/bin/perl

printf("char *helpstr=\"\\\n");
while (<>) {
    s/\@[A-z]+\{([^\{]*)\}/$1/g;
    s/\@[A-z]+\{([^\{]*)\}/$1/g;
    s/^\@.*//g;
    s/\@\@/\@/g;
    s/(.*)\n/$1/g;
    printf("%s\\n\\\n",$_); 
}
printf("\";\n");
